### ISSUE TITLE
Home page design

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-codergirlz#1]
Go off the flyer @irms gave you and design it to appeal to young females.

sites they like:
madewithcode.com
girldevelopit.com
100girlsofcode.com

due: 
9-28-15   12p

**Comment by vanderbeam** [comment]
@rodneystrong @irms 
![codergirlz-design](https://cloud.githubusercontent.com/assets/12962001/10066135/91868764-6244-11e5-9b55-6b55c4819575.png)

Home page for design idea:
- Nav: Colours will drop down when hovered
- Hovered links will be the darker pink on the site
- Picture of Margaret Hamilton is public domain

I used the css rule design because I thought it looked techy but there's an air of "girlishness" to curly brackets. I used proper punctuation in the main paragraph and semi-colons in the footer because I didn't think people who weren't familiar with code would know the semi-colon was a reference to code and not to grammar. I used classes because I think the pound sign would be associated with hashtags and not IDs. I collected a lot of the design aspects from the listed sites that all of them used (light background, cute colours, picture at the top, catch phrase on the picture). I used Margaret Hamilton because I felt like it was more meaningful than stock photography. However I realize the thought that placing images of tween girls using computers is important so they can relate to the website, so that's up for debate. 

Let me know if you like the direction. 
(uploaded the design picture to the actual github because I was in autopilot; it will be removed in the next push)

**Comment by rodneystrong** [comment]
Goooood shit good shit I like:

- the usage of CSS syntax throughout
- font choices
- layout
- changing colors over each nav item

Tell me more about why you chose: 

- the white dotted line to be in on the hero image
- the arrow pointers for different sections in the footer (CSS doesn't include those arrow pointers natively for each declaration)
- that specific color yellow/light green

*Start coding your mockup and upload the code here and make a gh-pages branch as usual*

Consider making this a single page site since the other "pages" don't have a lot of content. @irms any objections to that? I know the Shift3 proposal specifically stated "pages", but I imagine that term was loosely used for ease of explanation.

**Comment by vanderbeam** [comment]
- I tried a few different effects to break up the hero and also not make it look like the others (dashed lines were my favourite). I chose the lines because I feel dashed lines are a girlish effect opposed to a solid line. You see a lot of cute tumblr themes use them
- I can't seem to replicate it but when I've copied code into notepad, the ">" replace line numbers. I can take them out though since it's apparently not something consistent. 
- I found it in a colour palette and liked having a fifth colour that was neither teal nor pink. Something for smaller and fewer accents around the sites. 

And great! I can't wait to bring it to life! I'll keep an eye out for @irms 's input on pages v landing page.

**Comment by rodneystrong** [comment]
Gotcha. I think you already do a good job breaking up the space between the hero image and the body content with that dropshadow at the bottom of the hero image. I noticed those same tumblr themes too, but they also follow a fabric type of style which makes different elements on the site look embroidered. 

By tomorrow 10p, please recreate this mockup with these changes:

- remove the white dotted line in the hero image
-  remove the greater than arrow symbols in the footer
- change that yellow/light green color to #E0FB3B  (i got that from this palette I pulled from your original pink)

Upload that mockup here

**Comment by irms** [comment]
I don't personally like single page sites, and I think they'll want to add
things when they see it live. Let's go with multiple pages and use
additional imagery for space filling, please.

**Comment by dmpayton** [comment]
I have one minor text suggestion...

![females](https://cloud.githubusercontent.com/assets/149918/10112258/73f1f68e-638e-11e5-9357-de29af957fa0.png)

All I can think of is this...

![image](https://cloud.githubusercontent.com/assets/149918/10112262/835a54e0-638e-11e5-9750-419dbb6047b1.png)

But also, [this](http://jezebel.com/the-problem-with-calling-women-females-1683808274).

**Comment by rodneystrong** [comment]
@vanderbeam you heard the lady, build out the separate pages and find public domain licensed images we can use
