### ISSUE TITLE
Code the design

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-codergirlz#2]
Code the design you created in #1 
Dont forget to create a gh-pages branch
due:
9-28-15  6p

Updated due date:
9-28-15   10p

**Comment by vanderbeam** [comment]
@irms @rodneystrong 
With some review/input I should still be on track to make this deadline. See below for page note.

Home:
Except for cleaning up a margin here and there this page is ready for review (desktop and mobile views)

About Us:
Ditto

Curriculum:
Mobile version not done, would like input on direction of desktop though. Thinking about an effect to do when you hover. Since a couple aren't available in colour formats, I may just try to light something up in the grey scale with the hot pink. 

Chapters:
This is the idea I came up with. I'd like your input on this to see if I should continue with it or not. An example of what this design would look like mobile is available. 

Registration:
Not yet available. 


The GH-Page is live and up to date:
http://editllc.github.io/client-codergirlz

Thank you! :)

**Comment by irms** [comment]
@vanderbeam i'll let @rodneystrong handle the details, but this is generally looking good to me. Can you see what you think when you increase the font size significantly? Say 22px?

**Comment by rodneystrong** [comment]
Home and About look good. The links to "read more" on "about" dont work, but i'm sure you're already on that. 

Curriculum:
For the hover effect, go for it. No on the hot pink though. Go with the regular color versions of the logos and for CodeAvengers, use #D6443D and for GDI use #FA5A61

Chapters:
I don't know what's going on here. There are missing images also. Please flesh this design out more and fix the image links and then I'll review it. 

Good stuff so far! Keep it up.

**Comment by vanderbeam** [comment]
@rodneystrong 
Do you want me to create a wufoo account for this client or do we have information for one I should use for registration?

And for the fields, I was thinking:
Name
Email
Which school do you represent?
What interests you most about the program?

How's that?

And I'll have to look up what's going on with the link to that pdf in the first link. It either loads or times out. The second works fine for me though.

**Comment by rodneystrong** [comment]
I went through the spec and it didn't specifically state what service we'd use for the Registration form. 

Let's go with a Google Form. Create it under your account and create the fields you suggested, then embed the form into the page. Test it out and make sure the submissions go to you and then email me to test it as well. 

The second link on "About" does work now, good job.

**Comment by vanderbeam** [comment]
I think I'm going to need a little bit more time to finish this up. I'm redoing the Charter design and I've never used Google Form before. Should get the last two pages and Irma's suggestion done by the end of the night for sure though.

**Comment by irms** [comment]
I <3 everything here ;)

**Comment by rodneystrong** [comment]
Sure thing, **what day/time do you think you'll be able to complete all of this by?** Make the assumption that if you get stuck on embedding the Google Form I can help you right away with it.

**Comment by vanderbeam** [comment]
I will have a reviewable submission by 10pm tonight.

**Comment by rodneystrong** [comment]
Sounds good, I'll update the due date accordingly.

**Comment by vanderbeam** [comment]
@rodneystrong 
So it appears google forms aren't responsive.

**Comment by rodneystrong** [comment]
https://www.quora.com/How-do-I-make-a-Google-form-responsive-on-mobile

https://productforums.google.com/forum/m/#!topic/docs/uq5TMPPAPxU
On Sep 28, 2015 7:03 PM, "Meg M" <notifications@github.com> wrote:

@rodneystrong <https://github.com/rodneystrong>
So it appears google forms aren't responsive.

—
Reply to this email directly or view it on GitHub
<https://github.com/EditLLC/client-codergirlz/issues/2#issuecomment-143923565>
.

**Comment by vanderbeam** [comment]
http://editllc.github.io/client-codergirlz/index.html
@rodneystrong @irms 

- The code avengers and girl develop it images work but they're place holders for a moment (I have to switch computers to edit that file).
- Both of the "About Me" links work now
- I'm still working customizing the registration form. It automatically sends me an excell form and saves it in a folder in my Google Drive. Here's a link straight to the form: https://docs.google.com/forms/d/13_Wa5JSoHr3KoX-fmFZnqjTkEsd9G1kaM3WFxF8Tf6U/viewform
- I'm not happy with the design of the chapters so I welcome suggestions. The issue I keep running into is they want the school colours in the section but everything clashes with the site's colour palette (which is why I used their school logo in the samples). When I get an approved design for this it'll be a matter of copy/pasting so I'm not worried about that. I also plan on adding a chapter index to the top so people can jump down to their school. 

Everything is pretty much ready for review (mobile and vision). I'm jumping onto my pc now to make the other changes I needed. I figured I'd go ahead and let you guys know the status/get input whiel I did that.

**Comment by vanderbeam** [comment]
The links and images have been corrected. This is pretty much all ready for complete feedback. Also note that I decorated the scrollbar. Let me know if you like that or want the default back!

**Comment by rodneystrong** [comment]
Oh man that font size is way too big. Why did you use the "pt" unit instead of the "px" unit? Switch it to 22px please; after that feel free to increase or decrease slightly based on your judgement.

Good job on the google form and making it responsive. 

I tested the reg. form so let me know if you got my submission. Please make buildicus@gmail.com the owner of that google form now and invite alex@buildicus.com and irma@buildicus.com as editors.

The design of the chapters is perfectly fine; the color clashing will be an issue regardless and since they require the school colors there's no way around it. Finish filling in the rest of the schools.

The scrollbar's a nice added touch, good call.

**Comment by rodneystrong** [comment]
@irms i have a feeling she'll have these done by tomorrow 11a. Want to send the client the URL for initial review?

**Comment by irms** [comment]
@aleeex yes, thank you!

**Comment by rodneystrong** [comment]
@irms did the client see this by any chance?

**Comment by irms** [comment]
@rodneystrong they have, but I won't get any feedback until Monday at the meeting.

**Comment by rodneystrong** [comment]
@irms gotcha, thanks. can't wait to hear what they say.
