### ISSUE TITLE
Odd Height Layout on homepage

### ISSUE THREAD

**Issue by irms** [EditLLC/client-codergirlz#6]
This is maybe just my thing, but the way the page is laid out doesn't feel symmetrical. Is there anything we can do about it?
![codergirlz home](https://cloud.githubusercontent.com/assets/643997/10237347/26ad54aa-6865-11e5-86a7-ae50e13216c6.png)

**Comment by vanderbeam** [comment]
Well I can do one of a lot of things here. 
1) I can take out the closing curly bracket from all the paragraph's on the website or I can make it much smaller and more subtle so it'll take up less space
2) I can add a snippet of text there under the picture or add another picture

**Comment by irms** [comment]
I think I lean toward another picture.

**Comment by vanderbeam** [comment]
Let me know if you like this. I decided to take the "change the world" line and switch it into that column. http://editllc.github.io/client-codergirlz/

**Comment by irms** [comment]
so much better. Thanks!

**Comment by rodneystrong** [comment]
Yes, well done! 
A minor suggestion:
Remove the period after "Change the world". You do a good job differentiating the "Start coding" text from the "Change the world" that minimizes the need for a period. In fact, "Change the world" acts more like a title rather than a sentence in this case. 

I leave it up to you.
