### ISSUE TITLE
Title break

### ISSUE THREAD

**Issue by irms** [EditLLC/client-codergirlz#7]
The title at top breaks at certain sizes. @rodneystrong suggestions to fix?

<img width="622" alt="screenshot 2015-10-01 17 52 34" src="https://cloud.githubusercontent.com/assets/643997/10237363/5180854e-6865-11e5-8092-4d715e67275a.png">

**Comment by vanderbeam** [comment]
I can turn off word wrap and add some media queries maybe?

**Comment by rodneystrong** [comment]
checkin it out

**Comment by rodneystrong** [comment]
For the word-wrapping issue, you should check this out @vanderbeam   http://stackoverflow.com/questions/4652654/how-to-turn-off-word-wrapping-in-html 

But there's also a larger issue with code design/structure. You have the h2 as a child to a div that's been absolute positioned and given a percentage for a width instead of px units. The better way for responsiveness would've been to go with a margin: 0 auto on the parent div and to remove absolute positioning with the percentages. 

When you have a moment, review the commit history on this to see how I band-aid fixed it and then ask me questions on why I did what I did.

**Comment by rodneystrong** [comment]
Just pushed. You're definitely gonna want to PULL before you start making changes @vanderbeam

**Comment by vanderbeam** [comment]
@rodneystrong Ahhh... but I've already made a bunch of changes since my last pull.... what do I do?

**Comment by rodneystrong** [comment]
do a pull right now, and go ahead override my merge conflicts. essentially anything that's in the HEAD when you pull is what you'll keep. 

I can go back and fix your code again after you override mine.

**Comment by vanderbeam** [comment]
![head](https://cloud.githubusercontent.com/assets/12962001/10241627/7437efca-689f-11e5-9c10-b75a0ecc3c0e.png)

This is a conflict I'm getting. What were you doing here exactly? I don't want to accidentally override something from "HEAD" since you said not to.

**Comment by rodneystrong** [comment]
call me right now

**Comment by rodneystrong** [comment]
resolved.
